---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

commonLabels:
  component: minio

resources:
- namespace.yml
- pvc.yml
- secret.yml
- deployment.yml
- service.yml
- route.yml
